// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.
// Regenerate with: pnpm --filter @fable/sections generate
import type { RegistryEntry } from "./contract";
import * as contact_form from "./contact_form";
import * as cta_banner from "./cta_banner";
import * as faq_accordion from "./faq_accordion";
import * as feature_grid from "./feature_grid";
import * as gallery from "./gallery";
import * as hero from "./hero";
import * as image_text_split from "./image_text_split";
import * as logo_strip from "./logo_strip";
import * as rich_text from "./rich_text";
import * as testimonials from "./testimonials";

export const registry = {
  contact_form: { schema: contact_form.schema, meta: contact_form.meta, Component: contact_form.Component },
  cta_banner: { schema: cta_banner.schema, meta: cta_banner.meta, Component: cta_banner.Component },
  faq_accordion: { schema: faq_accordion.schema, meta: faq_accordion.meta, Component: faq_accordion.Component },
  feature_grid: { schema: feature_grid.schema, meta: feature_grid.meta, Component: feature_grid.Component },
  gallery: { schema: gallery.schema, meta: gallery.meta, Component: gallery.Component },
  hero: { schema: hero.schema, meta: hero.meta, Component: hero.Component },
  image_text_split: { schema: image_text_split.schema, meta: image_text_split.meta, Component: image_text_split.Component },
  logo_strip: { schema: logo_strip.schema, meta: logo_strip.meta, Component: logo_strip.Component },
  rich_text: { schema: rich_text.schema, meta: rich_text.meta, Component: rich_text.Component },
  testimonials: { schema: testimonials.schema, meta: testimonials.meta, Component: testimonials.Component },
} satisfies Record<string, RegistryEntry>;

export type SectionType = keyof typeof registry;

export function getRegistryEntry(type: string): RegistryEntry | null {
  return Object.hasOwn(registry, type)
    ? registry[type as SectionType]
    : null;
}
