/**
 * Generates src/registry.ts from the section directories in src/.
 * Run with: pnpm --filter @fable/sections generate
 * Never edit src/registry.ts by hand.
 */
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const srcDir = fileURLToPath(new URL("../src", import.meta.url));

const sectionDirs = readdirSync(srcDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && entry.name !== "lib")
  .map((entry) => entry.name)
  .sort();

for (const dir of sectionDirs) {
  if (!existsSync(join(srcDir, dir, "index.ts"))) {
    throw new Error(`section directory src/${dir} has no index.ts`);
  }
}

const lines = [
  "// AUTO-GENERATED by scripts/generate-registry.ts — do not edit.",
  "// Regenerate with: pnpm --filter @fable/sections generate",
  'import type { RegistryEntry } from "./contract";',
  ...sectionDirs.map((dir) => `import * as ${dir} from "./${dir}";`),
  "",
  "export const registry = {",
  ...sectionDirs.map(
    (dir) =>
      `  ${dir}: { schema: ${dir}.schema, meta: ${dir}.meta, Component: ${dir}.Component },`,
  ),
  "} satisfies Record<string, RegistryEntry>;",
  "",
  "export type SectionType = keyof typeof registry;",
  "",
  "export function getRegistryEntry(type: string): RegistryEntry | null {",
  "  return Object.hasOwn(registry, type)",
  "    ? registry[type as SectionType]",
  "    : null;",
  "}",
  "",
];

writeFileSync(join(srcDir, "registry.ts"), lines.join("\n"));
console.log(
  `Generated src/registry.ts with ${sectionDirs.length} sections: ${sectionDirs.join(", ")}`,
);
